### ISSUE TITLE
Error lambda cost_buddy

### ISSUE THREAD

**Issue by daviaro** [intuit/costBuddy#5]
Hello.

We carry out all the steps suggested on the page https://github.com/intuit/costBuddy once we finish the execution and finish successfully, we open GRAFANA to see the graphics nothing is perceived. When we go to see the record of the lambdas we see the following error:

![imagen](https://user-images.githubusercontent.com/6389962/77703053-d9965e80-6f87-11ea-82c7-a9ac36f63bdf.png)

thank you for your help.

**Comment by khilawar4** [comment]
Hi daviaro ,
Thanks for raising the issue. Can you please provide details.

1. Was this AWS account recently ?
2. Was CE(Cost Explorer) got enabled recently ?
3. is above error is during the first run of Lambda ?

Suggestion: 
If CE was enabled in less than 24 hours than u wont see the data as AWS CE billing report will be updated only after 24 hours after CE is enabled for the first time.

Also can you check if you see below error somewhere in lambda log.
**[ERROR] DataUnavailableException: An error occurred (DataUnavailableException) when calling the GetCostAndUsage operation: Data is not available. Please try to adjust the time period. If just enabled Cost Explorer, data might not be ingested yet**

**Comment by daviaro** [comment]
Hello khilawar4
I answer point by point below:

1. Was this AWS account recently ?
Yes, this account is recent. We opened it on March 11.

2. Was CE(Cost Explorer) got enabled recently ?
We enable the CE the same day the account was opened.

3. is above error is during the first run of Lambda ?
This error occurs every time the file was loaded at 11 at night every day. Until we decided to stop everything because the grafana did not present anything and the error sent on the screen or that we sent at the beginning of the thread was presented.

Finally, I inform you that we are going to execute the process again from the beginning and I will inform you again of the results.

Thank a lot.

**Comment by khilawar4** [comment]
sure let me know how it goes.

**Comment by daviaro** [comment]
Hello khilawar4!!

we execute the process again according to the guide and using fictitious accounts in the bills.xls file and we obtain the same result that I reported before. Below the screenshot:

![imagen](https://user-images.githubusercontent.com/6389962/77874603-090ccb80-7213-11ea-8485-3c28a108cbd9.png)

If you need more information please let me know.
Thank you very much again.

**Comment by khilawar4** [comment]
hey david , can u check manually in the CE report from AWS console if there are some cost showing in CE itself. as per the exception , looks like in CE report , no cost is showing. It could be possible that there are no resources running in your AWS accounts to generate cost. please let me know once u see the CE report manually. 
We can also try to join Zoom meeting or slack to help you troubleshoot the issue.

**Comment by khilawar4** [comment]
Hi daviaro
Do you need further assistance or can we close this issue.

**Comment by daviaro** [comment]
Sorry Khilawar4. yes of course we review our account and as it is new it does not have cost information, so we assume that it is the reason for the error that has been occurring. We will continue evaluating and we will inform you if we manage to overcome the error. For now it is best to close the case.

**Comment by daviaro** [comment]
thnks for your help

**Comment by khilawar4** [comment]
sure thx for the update.

Since there was no cost information available in CE api in user's aws account hence this issue was expected. We are closing this issue as there is no problem from code perspective.
