### ISSUE TITLE
Error in state machine execution

### ISSUE THREAD

**Issue by mohitk09** [intuit/costBuddy#6]
**Describe the bug**
I tried to reproduce the exact steps, but having trouble understanding this
https://github.com/intuit/costBuddy/blob/master/terraform/variables.tf#L2
I can't seem to understand the significance of it, what this layer contains? I removed this and deployed without this layer, and after that I get `Runtime.ImportModuleError: Unable to import module 'ce.process_daily_monthly_spend': Missing required dependencies ['numpy']`  even though I had listed `numpy` as a dependency and built the newer version of zip, but still I get this.

**To Reproduce**

1. Remove SciPy layer from everywhere in the code, list `numpy` in the dependency and build the new zip.
2. Try deploying it, the deployment is successful but on starting the state machine execution the `cost_buddy` lambda fails with an error stated above.

**Screenshots**

![Screenshot 2020-05-26 at 12 46 22 PM](https://user-images.githubusercontent.com/26171991/82871774-b4a27580-9f4f-11ea-9e20-3786de011ae4.png)
  

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**
Also are the account Id's hardcoded in this file? I think these are actual account Ids.
https://github.com/intuit/costBuddy/blob/master/terraform/variables.tf#L6

**Comment by sandipnahak** [comment]
Thanks for raising the issue. 

@mohitk09 NumPy package required by costbuddy to generate an excel sheet, which will be uploaded to an s3 bucket to further analyze the cost using AWS native tools like Athena, Quicksight. 

Can you please provide details.

1. How are you building the lambda layer?
2. What is the AWS region you are deploying to?
3. Post-deployment did you notice the lambda layer attached to the lambda function?

Thanks
Sandip

**Comment by mohitk09** [comment]
Hi, this is what I did
1. I have just included `numpy` as a dependency in this file.
https://github.com/intuit/costBuddy/blob/master/terraform/modules/layers/layers/requirements.txt
2. ran this script 
https://github.com/intuit/costBuddy/blob/master/terraform/modules/layers/layers/prep.sh
3. Then I compressed the directory and replaced it with this 
https://github.com/intuit/costBuddy/blob/master/terraform/modules/layers/costbuddy-lambda-layer.zip
4. I removed the sciPy layer as didn't know what's in that layer, I still don't understand this, whose accounts are these
https://github.com/intuit/costBuddy/blob/master/terraform/variables.tf#L2
5. I deployed in `eu-west-1` region 
6. Yes after deployment one layer was attached to the lambda by this name `cost_buddy_layer`.

Let me know if you require any more details. Thank you

**Comment by sandipnahak** [comment]
Building the layer locally might generate incompatible layer which might not work with python version 3.7. To avoid such issues and reduce artifact size, we are leveraging existing layers that are region-specific and readily available.

These lambda layers are AWS provided lambda layers, and account ids belong to AWS.

Please add the `eu-west-1` layer this list and run the terraform.

default = {
    "us-west-1" : "arn:aws:lambda:us-west-1:325793726646:layer:AWSLambda-Python37-SciPy1x:2",
    "us-west-2" : "arn:aws:lambda:us-west-2:420165488524:layer:AWSLambda-Python37-SciPy1x:2",
    "us-east-1" : "arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:2",
    "us-east-2" : "arn:aws:lambda:us-east-2:259788987135:layer:AWSLambda-Python37-SciPy1x:2",
   "eu-west-1" : "arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python37-SciPy1x:22"
}

**Comment by mohitk09** [comment]
Thank you, it has solved my issue, works fine now.
